apiVersion: v1
kind: Service
metadata:
  name: gcp-log-manager-service
spec:
  selector:
    app: gcp-log-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
